version: "3.4"

networks:
  db-net:

services:
  postgresql:
    image: bitnami/postgresql:11.7.0
    networks:
      - db-net
    volumes:
      - ./postgresql/DB:/bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: CMCSI@2018
    deploy:
      restart_policy:
        condition: on-failure