const object = {
    Batch__c: "[dbo].[Core_GetDataContinuouslyByObjectBatch]",
    Package__c: "[dbo].[Core_GetDataContinuouslyByObjectPackage]",
    Item__c: "[dbo].[Core_GetDataContinuouslyByObjectItem]",
    Receipt__c: "[dbo].[Core_GetDataContinuouslyByObjectReceipt]",
    Added_Value_in_Package__c: "[dbo].[Core_GetDataContinuouslyByObjectAddedValue]",
    Delivery: "[dbo].[Core_GetDataContinuouslyByObjectDelivery]"
}

const fields = {
    Batch__c: {
        Batch_Number__c: "Batch_Number__c",
        Numbers_Of_Item__c: "Numbers_Of_Item__c",
        Batch_Value__c: "Batch_Value__c",
        Real_Summary_Weight__c: "Real_Summary_Weight__c",
        Converted_Summary_Weight__c: "Converted_Summary_Weight__c",
        Batch_Cod__c: "Batch_Cod__c",
        Primary_Service__c: "Primary_Service__r.External_Service__c",
        Sending_Method__c: "Sending_Method__c",
        PO_Acceptance__c: "PO_Acceptance__r.Name"
    },
    Package__c: {
        Batch_Number__c: "Batch_Number__c",
        Package_Number__c: "Package_Number__c",
        // "Account__c": "Shopee - Beta Pickup - Liên tỉnh",
        Account_No__c: "Account_No__c",
        // Order_Code__c: "Order_Code__c",
        Location_Type__c: "Location_Type__c",
        Main_Freight__c: "Main_Freight__c",
        VAT_Freight__c: "VAT_Freight__c",
        Receive_Note__c: "Receive_Note__c",
        So_luong__c: "So_luong__c",
        Ten_hang_hoa__c: "Ten_hang_hoa__c",
        Gia_tri_hang_hoa__c: "Gia_tri_hang_hoa__c",
        COD_hang_hoa__c: "COD_hang_hoa__c",
        Length__c: "Length__c",
        Width__c: "Width__c",
        Height__c: "Height__c",
        Type_Of_Ship__c: "Type_Of_Ship__c",
        Total_Weight__c: "Total_Weight__c",
        Conv_Weight__c: "Conv_Weight__c",
        Primary_Service__c: "Primary_Service__r.External_Service__c",
        Purchase_Order__c: "Purchase_Order__c",
        Sending_Method__c: false, 
        Sender_Name__c: "Sender_Name__c",
        Sender_Phone__c: "Sender_Phone__c",
        Sender_Email__c: "Sender_Email__c",
        SenderCountryCode__c: "SenderCountryCode__r.Name",
        SendFullAddress__c: "SendFullAddress__c",
        SenderZipCode__c: "SenderZipCode__c",
        Shipping_Name__c: "Shipping_Name__c",
        Shipping_Phone__c: "Shipping_Phone__c",
        Shipping_Email__c: "Shipping_Email__c",
        "ReceiverCountryCode__c": "ReceiverCountryCode__r.Name",
        "ReceiverProvinceCode__c": "ReceiverProvinceCode__r.Name",
        "ReceiverDistrictCode__c": "ReceiverDistrictCode__r.Name",
        "ReceiverCommuneCode__c": "ReceiverCommuneCode__r.Name",
        ReceiverStreet__c: "ReceiverStreet__c",
        RecFullAddress__c: "RecFullAddress__c",
        ReceiverZipCode__c: "ReceiverZipCode__c",
        Datetime_Acceptanced__c: "Datetime_Acceptanced__c",
        "PO_Accept__c": "PO_Accept__r.Name",
        CountryDelivery__c: "CountryDelivery__c",
        //"CreatedById": "2020-09-13T07:35:45.957",
        OperInst__c: "OperInst__c",
        MainFreight__c: "MainFreight__c",
        OriVATFreight__c: "OriVATFreight__c",
        VATFreight__c: "VATFreight__c",
        OriToFreVAT__c: "OriToFreVAT__c",
        TotaFreVAT__c: "TotaFreVAT__c",
        OriToFreDiscVAT__c: "OriToFreDiscVAT__c",
        TotaFreDiscVAT__c: "TotaFreDiscVAT__c",
        TotaFreDiscount__c: "TotaFreDiscount__c",
        OrtherFreight__c: "OrtherFreight__c",
        TotaFre__c: "TotaFre__c",
        OriToFreDiscount__c: "OriToFreDiscount__c",
        AirSurFreight__c: "AirSurFreight__c",
        FarRegFreight__c: "FarRegFreight__c",
        OriFueSurFreight__c: "OriFueSurFreight__c",
        FueSurFreight__c: "FueSurFreight__c",
        OriginalSubFreight__c: "OriginalSubFreight__c",
        SubFreight__c: "SubFreight__c",
        OtherFreight__c: "OtherFreight__c",
        OriToFre__c: "OriToFre__c",
        OriPayFreight__c: "OriPayFreight__c",
        PaymentFreight__c: "PaymentFreight__c",
        OriPayFreight__c1: "OriPayFreight__c",
        RemainFreight__c: "RemainFreight__c",
        OriPayFreightVAT__c: "OriPayFreightVAT__c",
        PayFreightVAT__c: "PayFreightVAT__c",
        OriRemFreightVAT__c: "OriRemFreightVAT__c",
        RemainingFreightVAT__c: "RemainingFreightVAT__c",
        OriPayFreiDisc__c: "OriPayFreiDisc__c",
        PaymentFreiDisc__c: "PaymentFreiDisc__c",
        OriRemFreiDisc__c: "OriRemFreiDisc__c",
        RemFreiDisc__c: "RemFreiDisc__c",
        OriPayFreDiscVAT__c: "OriPayFreDiscVAT__c",
        PaymentFreDiscVAT__c: "PaymentFreDiscVAT__c",
        OriRemFreDiscVAT__c: "OriRemFreDiscVAT__c",
        RemFreDiscVAT__c: "RemFreDiscVAT__c",
        ValAddSerFreToFre__c: "ValAddSerFreToFre__c"
    },
    Item__c: {
        External_Item_Id__c: "External_Item_Id__c",
        Item_Code__c: "Package_Number__c",
        Detail_Item_Name__c: "Detail_Item_Name__c",
        Item_Amount__c: "Item_Amount__c",
        Commodity_Type_Code__c: "Commodity_Type_Code__c",
        Item_Vasproperty_Value__c: "Item_Vasproperty_Value__c"
    },
    Receipt__c: {
        Package_Number__c: "Package_Number__c",
        BD29_ID__c: "BD29_ID__c",
        //InsertedDate__c: "InsertedDate__c",
        POSCode__c: "POS_Code__r.Name",
        ShiftCode__c: "ShiftCode__c",
        Legacy_Account_ID__c: "Legacy_Account_ID__c",
        ValueAddedServicesCode__c: "ValueAddedServicesCode__c",
        KhoiLuongThuc__c: "KhoiLuongThuc__c",
        KhoiLuongQuyDoi__c: "KhoiLuongQuyDoi__c",
        CuocChinh__c: "CuocChinh__c",
        CuocGTGT__c: "CuocGTGT__c",
        CuocThuHoChiHo__c: "CuocThuHoChiHo__c",
        ThueVAT__c: "ThueVAT__c",
        TongTienMat__c: "TongTienMat__c",
        TongGhiNo__c: "TongGhiNo__c",
        CuocThuNguoiNhan__c: "CuocThuNguoiNhan__c",
        SoTienThuHo__c: "SoTienThuHo__c",
        BCCPUserName__c: "BCCPUserName__c",
        MachineName__c: "MachineName__c",
        CreatedDate__c: "CreatedDate__c",
        LastUpdatedTime__c: "LastUpdatedTime__c",
        AcceptancePOSCode__c: "Acceptance_POS_Code__r.Name",
        Batch_Number__c: "Order_Number__c"
    },
    Added_Value_in_Package__c: {
        External_AVP_Id__c: "External_AVP_Id__c",
        Tracking_Code__c: "Package_Number__c",
        COD_Delivery_Address__c: "COD_Delivery_Address__c",
        COD_Amount__c: "COD_Amount__c",
        COD_Fee__c: "COD_Fee__c",
        COD_Status_on_Paypost__c: "COD_Status_on_Paypost__c",
        COD_Fee_Payer__c: "COD_Fee_Payer__c",
        //Added_Value_Service_Name__c: "Phát hàng thu tiền",
        Added_Value_Service_Fee__c: "Added_Value_Service_Fee__c",
        // Service_Using_Customer__c: "Service_Using_Customer__c",
        Return_Date_Time__c: "Return_Date_Time__c",
        Return_Name__c: "Return_Name__c",
        Return_Street__c: "Return_Street__c",
        Return_Phone__c: "Return_Phone__c",
        Return_Country_Code__c: "Return_Country_Code__c",
        Generated_Tracking_Code__c: "Generated_Tracking_Code__c",
        Goods_Value__c: "Goods_Value__c"
    }
}

const fieldsf = {
    order: {
        Status: 'Status',
        From__c: 'From__c',
        EffectiveDate: 'EffectiveDate',
        SalesOrderNumber__c: 'SalesOrderNumber__c',
        'Account.Ma_khach_hang__c': 'Account.Ma_khach_hang__c',
        uuid_tracking__c: 'uuid_tracking__c',
        uuid__c: 'uuid_tracking__c'
    },
    batch__c: {
        Batch_Number__c: "Batch_Number__c",
        Numbers_Of_Item__c: "Numbers_Of_Item__c",
        Batch_Value__c: "Batch_Value__c",
        Real_Summary_Weight__c: "Real_Summary_Weight__c",
        Converted_Summary_Weight__c: "Converted_Summary_Weight__c",
        Batch_Cod__c: "Batch_Cod__c",
        "Primary_Service__r.External_Service__c": "Primary_Service__r.External_ID_BCCP__c",
        Sending_Method__c: "Sending_Method__c",
        From__c: "From__c",
        uuid_tracking__c: 'uuid_tracking__c',
        uuid__c: 'uuid_tracking__c'
    },
    package__c: {
        Batch_Number__c: "Batch_Number__c",
        Package_Number__c: "Package_Number__c",
        Account_No__c: "Account_No__c",
        // Order_Code__c: "Order_Code__c",
        Location_Type__c: "Location_Type__c",
        Main_Freight__c: "Main_Freight__c",
        VAT_Freight__c: "VAT_Freight__c",
        Receive_Note__c: "Receive_Note__c",
        So_luong__c: "So_luong__c",
        Ten_hang_hoa__c: "Ten_hang_hoa__c",
        Gia_tri_hang_hoa__c: "Gia_tri_hang_hoa__c",
        COD_hang_hoa__c: "COD_hang_hoa__c",
        Length__c: "Length__c",
        Width__c: "Width__c",
        Height__c: "Height__c",
        Type_Of_Ship__c: "Type_Of_Ship__c",
        Total_Weight__c: "Total_Weight__c",
        Conv_Weight__c: "Conv_Weight__c",
        "Primary_Service__r.External_Service__c": "Primary_Service__r.External_ID_BCCP__c",
        Purchase_Order__c: "Purchase_Order__c",
        Sender_Name__c: "Sender_Name__c",
        Sender_Phone__c: "Sender_Phone__c",
        Sender_Email__c: "Sender_Email__c",
        SendFullAddress__c: "SendFullAddress__c",
        SenderZipCode__c: "SenderZipCode__c",
        Shipping_Name__c: "Shipping_Name__c",
        Shipping_Phone__c: "Shipping_Phone__c",
        Shipping_Email__c: "Shipping_Email__c",
        ReceiverStreet__c: "ReceiverStreet__c",
        RecFullAddress__c: "RecFullAddress__c",
        ReceiverZipCode__c: "ReceiverZipCode__c",
        Datetime_Acceptanced__c: "Datetime_Acceptanced__c",
        CountryDelivery__c: "CountryDelivery__c",
        OperInst__c: "OperInst__c",
        MainFreight__c: "MainFreight__c",
        OriVATFreight__c: "OriVATFreight__c",
        VATFreight__c: "VATFreight__c",
        OriToFreVAT__c: "OriToFreVAT__c",
        TotaFreVAT__c: "TotaFreVAT__c",
        OriToFreDiscVAT__c: "OriToFreDiscVAT__c",
        TotaFreDiscVAT__c: "TotaFreDiscVAT__c",
        TotaFreDiscount__c: "TotaFreDiscount__c",
        OrtherFreight__c: "OrtherFreight__c",
        TotaFre__c: "TotaFre__c",
        OriToFreDiscount__c: "OriToFreDiscount__c",
        AirSurFreight__c: "AirSurFreight__c",
        FarRegFreight__c: "FarRegFreight__c",
        OriFueSurFreight__c: "OriFueSurFreight__c",
        FueSurFreight__c: "FueSurFreight__c",
        OriginalSubFreight__c: "OriginalSubFreight__c",
        SubFreight__c: "SubFreight__c",
        OtherFreight__c: "OtherFreight__c",
        OriToFre__c: "OriToFre__c",
        OriPayFreight__c: "OriPayFreight__c",
        PaymentFreight__c: "PaymentFreight__c",
        OriPayFreight__c1: "OriPayFreight__c",
        RemainFreight__c: "RemainFreight__c",
        OriPayFreightVAT__c: "OriPayFreightVAT__c",
        PayFreightVAT__c: "PayFreightVAT__c",
        OriRemFreightVAT__c: "OriRemFreightVAT__c",
        RemainingFreightVAT__c: "RemainingFreightVAT__c",
        OriPayFreiDisc__c: "OriPayFreiDisc__c",
        PaymentFreiDisc__c: "PaymentFreiDisc__c",
        OriRemFreiDisc__c: "OriRemFreiDisc__c",
        RemFreiDisc__c: "RemFreiDisc__c",
        OriPayFreDiscVAT__c: "OriPayFreDiscVAT__c",
        PaymentFreDiscVAT__c: "PaymentFreDiscVAT__c",
        OriRemFreDiscVAT__c: "OriRemFreDiscVAT__c",
        RemFreDiscVAT__c: "RemFreDiscVAT__c",
        ValAddSerFreToFre__c: "ValAddSerFreToFre__c",
        From__c: "From__c",
        uuid_tracking__c: 'uuid_tracking__c',
        uuid__c: 'uuid_tracking__c'
    },
    item__c: {
        External_Item_Id__c: "External_Item_Id__c",
        Item_Code__c: "Package_Number__c",
        Detail_Item_Name__c: "Detail_Item_Name__c",
        Item_Amount__c: "Item_Amount__c",
        Commodity_Type_Code__c: "Commodity_Type_Code__c",
        Item_Vasproperty_Value__c: "Item_Vasproperty_Value__c",
        From__c: "From__c",
        uuid_tracking__c: 'uuid_tracking__c',
        uuid__c: 'uuid_tracking__c'
    },
    receipt__c: {
        Package_Number__c: "Package_Number__c",
        BD29_ID__c: "BD29_ID__c",
        // POSCode__c: "POS_Code__r.Name",
        ShiftCode__c: "ShiftCode__c",
        Legacy_Account_ID__c: "Legacy_Account_ID__c",
        ValueAddedServicesCode__c: "ValueAddedServicesCode__c",
        KhoiLuongThuc__c: "KhoiLuongThuc__c",
        KhoiLuongQuyDoi__c: "KhoiLuongQuyDoi__c",
        CuocChinh__c: "CuocChinh__c",
        CuocGTGT__c: "CuocGTGT__c",
        CuocThuHoChiHo__c: "CuocThuHoChiHo__c",
        ThueVAT__c: "ThueVAT__c",
        TongTienMat__c: "TongTienMat__c",
        TongGhiNo__c: "TongGhiNo__c",
        CuocThuNguoiNhan__c: "CuocThuNguoiNhan__c",
        SoTienThuHo__c: "SoTienThuHo__c",
        BCCPUserName__c: "BCCPUserName__c",
        MachineName__c: "MachineName__c",
        CreatedDate__c: "CreatedDate__c",
        LastUpdatedTime__c: "LastUpdatedTime__c",
        Batch_Number__c: "Order_Number__c",
        From__c: "From__c",
        uuid_tracking__c: 'uuid_tracking__c',
        uuid__c: 'uuid_tracking__c',
        External_Receipt_Id__c: 'External_Receipt_Id__c'
    },
    added_value_in_package__c: {
        External_AVP_Id__c: "External_AVP_Id__c",
        Tracking_Code__c: "Package_Number__c",
        COD_Delivery_Address__c: "COD_Delivery_Address__c",
        COD_Amount__c: "COD_Amount__c",
        COD_Fee__c: "COD_Fee__c",
        COD_Status_on_Paypost__c: "COD_Status_on_Paypost__c",
        COD_Fee_Payer__c: "COD_Fee_Payer__c",
        Added_Value_Service_Fee__c: "Added_Value_Service_Fee__c",
        Return_Date_Time__c: "Return_Date_Time__c",
        Return_Name__c: "Return_Name__c",
        Return_Street__c: "Return_Street__c",
        Return_Phone__c: "Return_Phone__c",
        Return_Country_Code__c: "Return_Country_Code__c",
        Generated_Tracking_Code__c: "Generated_Tracking_Code__c",
        Goods_Value__c: "Goods_Value__c",
        From__c: "From__c",
        uuid_tracking__c: 'uuid_tracking__c',
        uuid__c: 'uuid_tracking__c'
    }
}

const externalIds = {
    batch__c: 'Batch_Number__c',
    package__c: 'Package_Number__c',
    item__c: 'External_Item_Id__c',
    receipt__c: 'External_Receipt_Id__c',
    added_value_in_package__c: 'External_AVP_Id__c',
    delivery: ''
}

module.exports = {
    object,
    fields,
    fieldsf,
    externalIds
}
